module QuestionsHelper

  COURSES = ["CISC","BIOL","PSYC", "ANAT","ANCH","AODA","APSC","ARAB","ARTC","ARTF","ARTH","BCHM","BIOL","BIOM","BIOT","BISC","BMED","CDNS","CHEE","CHEM","CHIN","CISC","CIVL","CLAS","CMC","CMPE","COCA","COGS","COMM","COMP","CWRI","DEVS","DRAM","ECON","EDST","EDUC","ELEC","ENGL","FILM","FREN","GEOL","GPHY","GREK","GRMN","HIST","HLTH","LAW","LING","LISC","MATH","MBIO","MUSC","NURS","PHAR","PHIL","PHYS","SPAN","WRTI"]

end
